language: r
cache:
  - $HOME/.ccache
  - packages
cran: https://cloud.r-project.org
jobs:
  include:
  - os: linux
    dist: xenial
    r: oldrel
    addons:
      apt:
        sources:
        - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
        packages:
        - ccache
        - gdal-bin
        - libgdal-dev
        - libgdal1-dev
        - libgeos-dev
        - libnlopt-dev
        - libproj-dev
        - libudunits2-dev
    services:
      - xvfb
    before_install:
      - echo 'options(repos = c(CRAN = "https://packagemanager.rstudio.com/all/__linux__/xenial/latest"))' >> ~/.Rprofile.site
      - echo 'options(HTTPUserAgent = paste0("R/", getRversion(), " R (", paste(getRversion(), R.version["platform"], R.version["arch"], R.version["os"]), ")"))' >> ~/.Rprofile.site
      - mkdir $HOME/.R && echo -e 'CXX_STD = CXX14\n\nVER=\nCCACHE=ccache\nCC=$(CCACHE) gcc$(VER) -std=gnu99\nCXX=$(CCACHE) g++$(VER)\nC11=$(CCACHE) g++$(VER)\nC14=$(CCACHE) g++$(VER)\nFC=$(CCACHE) gfortran$(VER)\nF77=$(CCACHE) gfortran$(VER)' > $HOME/.R/Makevars
      - echo -e 'max_size = 5.0G\nsloppiness = include_file_ctime\nhash_dir=false' > $HOME/.ccache/ccache.conf
    before_script:
      - Rscript -e 'install.packages("igraph", type = "source")'
  - os: linux
    dist: xenial
    r: release
    addons:
      apt:
        sources:
        - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
        packages:
        - ccache
        - gdal-bin
        - libgdal-dev
        - libgdal1-dev
        - libgeos-dev
        - libnlopt-dev
        - libproj-dev
        - libudunits2-dev
    before_install:
      - echo 'options(repos = c(CRAN = "https://packagemanager.rstudio.com/all/__linux__/xenial/latest"))' >> ~/.Rprofile.site
      - echo 'options(HTTPUserAgent = paste0("R/", getRversion(), " R (", paste(getRversion(), R.version["platform"], R.version["arch"], R.version["os"]), ")"))' >> ~/.Rprofile.site
      - mkdir $HOME/.R && echo -e 'CXX_STD = CXX14\n\nVER=\nCCACHE=ccache\nCC=$(CCACHE) gcc$(VER) -std=gnu99\nCXX=$(CCACHE) g++$(VER)\nC11=$(CCACHE) g++$(VER)\nC14=$(CCACHE) g++$(VER)\nFC=$(CCACHE) gfortran$(VER)\nF77=$(CCACHE) gfortran$(VER)' > $HOME/.R/Makevars
      - echo -e 'max_size = 5.0G\nsloppiness = include_file_ctime\nhash_dir=false' > $HOME/.ccache/ccache.conf
    before_script:
      - Rscript -e 'install.packages("igraph", type = "source")'
    r_packages:
      - covr
    r_github_packages:
      - jimhester/lintr
    after_success:
    - Rscript -e 'covr::coveralls(type = "all", quiet = FALSE)'
    - Rscript -e 'lintr::lint_package()'
  - os: linux
    dist: xenial
    r: devel
    addons:
      apt:
        sources:
        - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
        packages:
        - ccache
        - gdal-bin
        - libgdal-dev
        - libgdal1-dev
        - libgeos-dev
        - libnlopt-dev
        - libproj-dev
        - libudunits2-dev
    before_install:
      - echo 'options(repos = c(CRAN = "https://packagemanager.rstudio.com/all/__linux__/xenial/latest"))' >> ~/.Rprofile.site
      - echo 'options(HTTPUserAgent = paste0("R/", getRversion(), " R (", paste(getRversion(), R.version["platform"], R.version["arch"], R.version["os"]), ")"))' >> ~/.Rprofile.site
      - mkdir $HOME/.R && echo -e 'CXX_STD = CXX14\n\nVER=\nCCACHE=ccache\nCC=$(CCACHE) gcc$(VER) -std=gnu99\nCXX=$(CCACHE) g++$(VER)\nC11=$(CCACHE) g++$(VER)\nC14=$(CCACHE) g++$(VER)\nFC=$(CCACHE) gfortran$(VER)\nF77=$(CCACHE) gfortran$(VER)' > $HOME/.R/Makevars
      - echo -e 'max_size = 5.0G\nsloppiness = include_file_ctime\nhash_dir=false' > $HOME/.ccache/ccache.conf
    before_script:
      - Rscript -e 'install.packages("igraph", type = "source")'
#  - os: osx
#    osx_image: xcode9.4
#    latex: false
#    r_build_args: '--no-build-vignettes'
#    r_check_args: '--as-cran --ignore-vignettes --no-examples'
#    before_install:
#    - Rscript -e "install.packages('digest', type = 'source')"
#    - Rscript -e "install.packages('fastshp', repos = 'https://rforge.net', type = 'source')"
r_build_args: " "
r_check_args: "--as-cran"
warnings_are_errors: true
notifications:
  email:
    on_success: change
    on_failure: change
branches:
  only:
    - master
    - development
