language: r
r:
  - oldrel
  - release
  - devel

cache: packages

addons:
  apt:
    packages:
    - tcl8.5-dev
    - tk8.5-dev

r_binary_packages:
  - matrixStats

r_github_packages:
  - jimhester/covr

warnings_are_errors: true

before_install:
  - tlmgr install xcolor
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

after_success:
  - Rscript -e 'covr::coveralls(coverage = print(covr::package_coverage(quiet = FALSE)))'

notifications:
  email:
    on_success: change
    on_failure: change
