# Sample .travis.yml for R projects.
#
# See README.md for instructions, or for more configuration options,
# see the wiki:
#   https://github.com/craigcitro/r-travis/wiki

sudo: required

language: r
cran: https://cran.rstudio.com/

env:
  global:
    - secure: "KxcKSH4TFMbNMKAj6ePl4yq6SCeYQJcDkw0PMuEdImomwxqY3mP8p+GWVmNN1PKl8k7C/rgLNPAiBoJmddXMzFvGoGRWvyeER0lDN49rzNPHANF9wnMBBYN27mp98hBZlX2Vxu48M3jbmy+wRpmKKvKxTxOa8tUkt0GVEUTPeGQ="

matrix:
  include:

#  - os: linux
#    dist: trusty
#    r: oldrel
#    before_install:
#    - export DISPLAY=:99.0
#    - sh -e /etc/init.d/xvfb start
#    - echo "options(repos = c(CRAN='https://cran.rstudio.com'))" >> ~/.Rprofile

  - os: linux
    dist: trusty
    before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - echo "options(repos = c(CRAN='https://cran.rstudio.com'))" >> ~/.Rprofile
    - chmod 755 ./_push_vignettes.sh
    after_success:
    - ./_push_vignettes.sh

  - os: linux
    dist: trusty
    r: devel
    before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - echo "options(repos = c(CRAN='https://cran.rstudio.com'))" >> ~/.Rprofile

  - os: osx
    osx_image: xcode8
    cran: https://cran.rstudio.com/
    latex: false
    r_build_args: '--no-build-vignettes'
    r_check_args: '--as-cran --ignore-vignettes --no-examples'
    before_install:
    - echo "options(repos = c(CRAN='https://cran.rstudio.com'))" >> ~/.Rprofile

r_build_args: " "

r_check_args: "--as-cran"

warnings_are_errors: true

r_binary_packages:
  - car
  - CircStats
  - data.table
  - Hmisc
  - matrixStats
  - plyr
  - raster
  - rgeos
  - sp

notifications:
  email:
    on_success: change
    on_failure: change

branches:
  only:
    - master

after_success:
  - Rscript -e 'covr::coveralls(coverage = print(covr::package_coverage(quiet = FALSE)))'

