sudo: required
language: r
cache: packages
cran: https://cran.rstudio.com/
matrix:
  include:
  - os: linux
    dist: trusty
    r: 3.3.0
    addons:
      apt:
        sources:
        - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
        packages:
        - libgdal1-dev
        - libnlopt-dev
        - libproj-dev
    before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    r_binary_packages:
      - survival
  - os: linux
    dist: trusty
    r: oldrel
    addons:
      apt:
        sources:
        - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
        packages:
        - libgdal1-dev
        - libnlopt-dev
        - libproj-dev
    before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
  - os: linux
    dist: trusty
    r: release
    addons:
      apt:
        sources:
        - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
        packages:
        - libgdal1-dev
        - libnlopt-dev
        - libproj-dev
    before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    r_binary_packages:
      - covr
    r_github_packages:
      - jimhester/lintr
    r_packages:
      - devtools
    after_success:
    - Rscript -e 'covr::coveralls(type = "all", quiet = FALSE)'
    - Rscript -e 'lintr::lint_package()'
  - os: linux
    dist: trusty
    r: devel
    addons:
      apt:
        sources:
        - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
        packages:
        - libgdal1-dev
        - libnlopt-dev
        - libproj-dev
    before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    r_packages:
    - devtools
  - os: osx
    osx_image: xcode9.1
    latex: false
    r_build_args: '--no-build-vignettes'
    r_check_args: '--as-cran --ignore-vignettes --no-examples'
r_build_args: " "
r_check_args: "--as-cran"
warnings_are_errors: true
notifications:
  email:
    on_success: change
    on_failure: change
branches:
  only:
    - master
    - development
