language: r
r:
  - oldrel
  - release
  - devel

cache: packages

warnings_are_errors: true

before_install:
  - tlmgr install xcolor
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

notifications:
  email:
    on_success: change
    on_failure: change
