# Sample .travis.yml for R projects.
#
# See README.md for instructions, or for more configuration options,
# see the wiki:
#   https://github.com/craigcitro/r-travis/wiki

sudo: required

language: r

cran: https://cran.rstudio.com/

env:
  global:
    - secure: "KxcKSH4TFMbNMKAj6ePl4yq6SCeYQJcDkw0PMuEdImomwxqY3mP8p+GWVmNN1PKl8k7C/rgLNPAiBoJmddXMzFvGoGRWvyeER0lDN49rzNPHANF9wnMBBYN27mp98hBZlX2Vxu48M3jbmy+wRpmKKvKxTxOa8tUkt0GVEUTPeGQ="

matrix:
  include:

  - os: linux
    dist: trusty
    r: oldrel
    addons:
      apt:
        packages:
        - libgdal1-dev
        - libproj-dev
    before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start


  - os: linux
    dist: trusty
    r: release
    addons:
      apt:
        packages:
        - libgdal1-dev
        - libproj-dev
    before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - chmod 755 ./_push_vignettes.sh
    - Rscript -e 'install.packages("dplyr", dependencies = TRUE)'
    r_binary_packages:
    - covr
    after_success:
    - ./_push_vignettes.sh
    - Rscript -e 'covr::coveralls(coverage = print(covr::package_coverage(quiet = FALSE)))'

  - os: linux
    dist: trusty
    r: devel
    addons:
      apt:
        packages:
        - libgdal1-dev
        - libproj-dev
    before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start

  - os: osx
    osx_image: xcode8.2
    latex: false
    r_build_args: '--no-build-vignettes'
    r_check_args: '--as-cran --ignore-vignettes --no-examples'
    before_script:
    - Rscript -e "install.packages('Rcpp', type = 'source')"

r_build_args: " "

r_check_args: "--as-cran"

warnings_are_errors: true

notifications:
  email:
    on_success: change
    on_failure: change

branches:
  only:
    - master
    - development
